# Generated by Django 2.2.4 on 2019-08-23 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('C', 'Complete'), ('D', 'Delivered')], default='P', max_length=1)),
                ('amount', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product_catagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Catagory_name', models.CharField(max_length=64, verbose_name='Catagory Name')),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topping_name', models.CharField(max_length=25, verbose_name='Topping')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=64)),
                ('prize_small', models.FloatField(verbose_name='Prize for Small')),
                ('prize_large', models.FloatField(verbose_name='Prize for Large')),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_catagory', to='orders.Product_catagory')),
            ],
        ),
        migrations.CreateModel(
            name='Order_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('rate', models.FloatField(default=0)),
                ('order_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='orders.Order')),
                ('product_detail', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='product_detail', to='orders.Product')),
                ('topping', models.ManyToManyField(blank=True, related_name='order_topping', to='orders.Topping')),
            ],
        ),
    ]
