# Generated by Django 2.1.7 on 2019-09-03 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_product_generic_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='generic_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
