# Generated by Django 2.1.7 on 2019-09-04 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20190903_0929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prize_large',
            new_name='price_large',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='prize_small',
            new_name='price_small',
        ),
    ]
